---
- name: Deploy Apache and Copy Files
  hosts: all
  become: yes

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started

    - name: Copy files to Apache document root
      copy:
        src: "."
        dest: "/var/www/html/"
